services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/vendor
    ports:
      - "8181:8181"
    command: php artisan serve --host=0.0.0.0 --port=8181
